#!/usr/bin/env bash
# take parameter from console
# transfers a file from our client to a server
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

src_path="$1"
ip="$2"
username="$3"
dst_path="$4"

scp -i "$dst_path" "$src_path" "$username"@"$ip":~
