#!/usr/bin/env bash
# Bash script that configures an Nginx server so that
# /redirect_me is redirecting to a “301 Moved Permanently”.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.facebook.com/Abdelilah.bch99;
    }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart

