#!/usr/bin/env bash
# Bash script that configures an Nginx server so that
# /redirect_me is redirecting to a “301 Moved Permanently” and 404 page.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
var = $(localhost)
new_string2 = "server {\n\tadd_header X-Server-By $var"
printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;
        location / {
                try_files $uri $uri/ =404;
        }
        location /redirect_me {
                return 301 https://www.facebook.com/Abdelilah.bch99;
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
        }
        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html;
                internal;
        }
}" > /etc/nginx/sites-enabled/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default
sudo service nginx restart
