#!/usr/bin/env bash
#installs and configures HAproxy in a LBServer
# Update package lists
sudo apt-get update -y

# Install HAProxy
sudo apt-get install -y haproxy

# Backup the original HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Create a new HAProxy configuration
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

frontend BCH-frontend
        bind *:80
        default_backend BCH-servers

backend BCH-servers-backend
        balance roundrobin
        server 365195-web-01 34.207.227.114 check
        server 365195-web-02 54.234.74.33 check
EOL

# Enable HAProxy to start during system boot
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy to apply the changes
sudo service haproxy start
