#!/usr/bin/env bash
# test if a host id on the network is active or not
# by sends an Internet Control Message Protocol 
# (ICMP) Echo Request packet to the target host.
# The target host receives the packet and processes it.
# If the target host is online and reachable,
# it responds with an ICMP Echo Reply packet.
# The source computer receives the reply packet
# and measures the round-trip time (RTT) it took for
# the packet to travel from the source to the target and back.
if [ $# -lt 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi