#!/usr/bin/env bash
#while loop and if and elif
while((i<10))
do
	if ((i == 3))
	then
		echo "bad luck"
		((i++))
	elif ((i==7))
	then
		echo "good luck"
		((i++))
	fi
	echo "Best School"
	((i++))
done
